### ISSUE TITLE
Set low value and up value not correctly updated swift

### ISSUE THREAD

**Issue by ghost** [AlexeyIS/RangeControl#1]
Hello  @AlexeyIS ,

I am developing an iPhone application with integrating Range Control. Is there any way I can Change Low value Or up Value of range controller . Because sometimes i want to change position of range controller. When i've set up or low value the range controller disappear from screen  Come to main point.

For Example : First Time Range Controller show on Screen 
                        Up Value = 0.6
                        Low Value = 0.4
working perfectly which i want but when i've change the low or up value they disappear from screen means 
                        Up Value = 0.9
                        Low Value = 0.3
Could you please suggest a way ASAP to change up or low values

**Comment by AlexeyIS** [comment]
Hi @shamdass, what device are trying to test with? Do you have a code snippet when it doesn't work? 
In general you can set up and low values like this: 
`self.rangeControl.lowValue = 0.3
self.rangeControl.upValue = 0.9`

**Comment by ghost** [comment]
Hello @AlexeyIS 
What device are trying to test with? 
**Comments:**   iPhone X
Do you have a code snippet when it doesn't work?
**Comments:**   No
In general you can set up and low values like this:
self.rangeControl.lowValue = 0.3 self.rangeControl.upValue = 0.9
**Comments:**  Okay i will check again  and let you know
